runtime: nodejs18
env: standard

instance_class: F2

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 1

env_variables:
  DISCORD_BOT_TOKEN: 
  GOOGLE_CLIENT_ID: 
  GOOGLE_CLIENT_SECRET: 
  OKTO_CLIENT_API_KEY: 
